apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: video-api
        image: ghcr.io/nthu-lsalab/nthu-distributed-system:latest
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 8081
        - name: prometheus
          containerPort: 2222
        command:
        - /cmd
        - video
        - api
        env:
        - name: KAFKA_PRODUCER_ADDRS
          value: kafka:9092
        - name: KAFKA_PRODUCER_TOPIC
          value: video
        - name: METER_HISTOGRAM_BOUNDARIES
          value: 10,100,200,500,1000
        - name: METER_NAME
          value: video.api
        - name: MINIO_BUCKET
          value: videos
        - name: MINIO_ENDPOINT
          value: play.min.io
        - name: MINIO_PASSWORD
          value: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
        - name: MINIO_USERNAME
          value: Q3AM3UQ867SPQQA43P2F
        - name: MONGO_DATABASE
          value: nthu_distributed_system
        - name: MONGO_URL
          value: mongodb://mongodb:27017/
        - name: REDIS_ADDR
          value: redis:6379
        - name: COMMENT_SERVER_ADDR
          value: comment-api:80
        resources:
          requests:
            memory: 30Mi
            cpu: 10m
          limits:
            memory: 60Mi
            cpu: 20m
