apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
rules:
- apiGroups:
  - apps
  - batch
  resources:
  - "*"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
