kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-actions
subjects:
- kind: ServiceAccount
  name: github-actions
roleRef:
  kind: Role
  name: github-actions
  apiGroup: rbac.authorization.k8s.io
